# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Patchloom.Patchloom
PackageVersion: 0.37.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: patchloom.exe
  PortableCommandAlias: patchloom
UpgradeBehavior: install
ReleaseDate: 2026-10-08
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/patchloom/patchloom/releases/download/patchloom-v0.37.1/patchloom-x86_64-pc-windows-msvc.zip
  InstallerSha256: 5ED64EEB729A433F40D82A46EBB9FDB23EB15FC63CA345EB5895DEDF44407B70
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://github.com/patchloom/patchloom/releases/download/patchloom-v0.37.1/patchloom-aarch64-pc-windows-msvc.zip
  InstallerSha256: 9D285679D36892B54663765716202371405F349F081A7984FB0A17A144D3CFED
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.12.0
