PackageIdentifier: Wiremux.Wiremux
PackageVersion: 0.9.3
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: wiremux.exe
  PortableCommandAlias: wiremux
ArchiveBinariesDependOnPath: true
Commands:
- wiremux
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/wiremuxhq/wiremux/releases/download/v0.9.3/wiremux-x86_64-pc-windows-msvc.zip
  InstallerSha256: 6CD0E79DD36DB0E19F1E6C74B93916C6E1B9F92FBD130CDCCC0E2A038D6DE064
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ManifestType: installer
ManifestVersion: 1.12.0
